### ISSUE TITLE
Can't play Subtitles

### ISSUE THREAD

**Issue by kingpager** [Kirari04/videocms#58]
Can not playing subtitles in Video.

And can you please make Download in player optional, i mean enable or disable Download.

Here is Error:
![videocms](https://github.com/Kirari04/videocms/assets/168208532/2a056b72-3909-4188-a9fa-374f3d3624b7)

**Comment by Kirari04** [comment]
Hi @kingpager 
I just pushed an update, you can pull the new images from Docker.
Let me know if this fixes the issue.

**Comment by kingpager** [comment]
Subtitles still not fixed.

**Comment by kingpager** [comment]
Okay is fixed. Thank you

And what about the download enabble or disable option in Player?

**Comment by Kirari04** [comment]
There is no such functionality rn, but you can create a pr if you want to implement it yourself.
